#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read package.json
const packageJsonPath = path.resolve(__dirname, "../package.json");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));

// Generate version.ts file
const versionContent = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION = "${packageJson.version}";
`;

const versionFilePath = path.resolve(__dirname, "../src/version.ts");
fs.writeFileSync(versionFilePath, versionContent);

console.log(`Generated version.ts with version: ${packageJson.version}`);
